[project]
name = "anyflip-get"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.4.1",
    "pillow>=12.2.0",
    "rich>=15.0.0",
]

[tool.uv]
package = true

[project.scripts]
anyflip-get = "anyflip_get.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/anyflip_get"]
